const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  login: (username, password) => ipcRenderer.invoke('login', username, password),
  getUsers: () => ipcRenderer.invoke('getUsers'),
  createUser: (username, password, role) => ipcRenderer.invoke('createUser', username, password, role),
  deleteUser: (id) => ipcRenderer.invoke('deleteUser', id),
  updateUser: (id, username, role, password) => ipcRenderer.invoke('updateUser', id, username, role, password),
  ping: () => ipcRenderer.invoke('ping'),
  getPatients: () => ipcRenderer.invoke('getPatients'),
  getPatientById: (id) => ipcRenderer.invoke('getPatientById', id),
  createPatient: (name, phone, dob, gender, address) => ipcRenderer.invoke('createPatient', name, phone, dob, gender, address),
  updatePatient: (id, name, phone, dob, gender, address) => ipcRenderer.invoke('updatePatient', id, name, phone, dob, gender, address),
  deletePatient: (id) => ipcRenderer.invoke('deletePatient', id),
  getSessions: () => ipcRenderer.invoke('getSessions'),
  getSessionsByPatient: (patientId) => ipcRenderer.invoke('getSessionsByPatient', patientId),
  getSessionById: (id) => ipcRenderer.invoke('getSessionById', id),
  createSession: (pId, date, amount, note, pkgId, diag, act, maladi, radio) => ipcRenderer.invoke('createSession', pId, date, amount, note, pkgId, diag, act, maladi, radio),
  updateSession: (id, pId, date, amount, note, pkgId, diag, act, maladi, radio) => ipcRenderer.invoke('updateSession', id, pId, date, amount, note, pkgId, diag, act, maladi, radio),
  deleteSession: (id) => ipcRenderer.invoke('deleteSession', id),
  selectRadioFile: () => ipcRenderer.invoke('selectRadioFile'),
  saveRadioFromPath: (path) => ipcRenderer.invoke('saveRadioFromPath', path),
  openRadioFile: (fileName) => ipcRenderer.invoke('openRadioFile', fileName),
  readRadioFile: (fileName) => ipcRenderer.invoke('readRadioFile', fileName),
  getPackages: () => ipcRenderer.invoke('getPackages'),
  getPackageById: (id) => ipcRenderer.invoke('getPackageById', id),
  getPackagesByPatient: (patientId) => ipcRenderer.invoke('getPackagesByPatient', patientId),
  getSessionsByPackage: (packageId) => ipcRenderer.invoke('getSessionsByPackage', packageId),
  createPackage: (patient_id, name, total_price, diagnostic, acr, radio_path) => ipcRenderer.invoke('createPackage', patient_id, name, total_price, diagnostic, acr, radio_path),
  updatePackage: (id, patient_id, name, total_price, diagnostic, acr, radio_path) => ipcRenderer.invoke('updatePackage', id, patient_id, name, total_price, diagnostic, acr, radio_path),
  deletePackage: (id) => ipcRenderer.invoke('deletePackage', id),
  getPrinters: () => ipcRenderer.invoke('getPrinters'),
  printThermalReceipt: (htmlContent, printerName) => ipcRenderer.invoke('printThermalReceipt', htmlContent, printerName)
});
